### PR TITLE
Fix Panic in Go 1.6

### LINKED ISSUE #23: Go 1.6 Panic: cgo argument has Go pointer to Go pointer
Go 1.6 is more restrict about passing pointers to cgo.
golang/go#12416

Passing a pointer to go pointer causes the following panic in iconv-go:

runtime.errorString: runtime error: cgo argument has Go pointer to Go pointer
  File "runtime/panic.go", line 426, in gopanic
    reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
  File "runtime/cgocall.go", line 499, in cgoCheckArg
    panic(errorString(msg))
  File "runtime/cgocall.go", line 373, in cgoCheckPointer
    cgoCheckArg(pt.elem, p, true, false, cgoCheckPointerFail)
  File "github.com/djimenez/iconv-go/converter.go", line 83, in Convert
    _, err = C.iconv(this.context, &inputPointer, &inputLeft, &outputPointer, &outputLeft)
  File "github.com/djimenez/iconv-go/converter.go", line 123, in ConvertString
    bytesRead, bytesWritten, err = this.Convert(inputBuffer[totalBytesRead:], outputBuffer[totalBytesWritten:])

### PR DESCRIPTION
**Pull request by kowalczykp**
This should fix #23 unfortunately it uses additional allocation using malloc, but I didn't come up with a different solution to avoid passing pointer to go pointer into iconv (cgo). I tried to stick to the naming convention used in the code, although it became a bit too long around shift tracking.

Existent tests and examples seem to be working now both with go <1.6 and 1.6

### CODE REVIEW

**Comment by kowalczykp** [comment]
sorry, for late answer - been busy. 

@dimandzhi Thanks for pointing that out :+1:  Storing a pointer in C was a great hint, although cgo is not guaranteed to run in single thread even with GOMAXPROC==1, so having a global pointer in C and returning it's address would lead to panics. Alternative would be to make some table in C to store the pointers and make it thread-safe, but that would be still messy.

Apparently the simplest thing to be done, was to write a wrapper around iconv, which allows to omit the unnecessary allocations and go back to previous way of handling pointer shifting, without the mess I introduced  ;) 

 ```c
size_t call_iconv(iconv_t ctx, char *in, size_t *size_in, char *out, size_t *sizeout){
	return iconv(ctx, &in, size_in, &out, sizeout);
}
```

As for your last question, passing a slice as a parameter into function does not involve any copying of the slice content. 

> A slice is a descriptor of an array segment. It consists of a pointer to the array, the length of the segment, and its capacity (the maximum length of the segment).

**Comment by djimenez** [comment]
with you did with call_iconv wrapper looks like what I expected would end up being the solution i thnk, so now I have confirmation bias.

can you squash your commits and reference the issue number in the commit message?

**Comment by kowalczykp** [comment]
Since, the approach (fortunately) changed, the byteSliceToC helper func could have been omitted as well as the white space

If that bothers you I can remove both with another squashing

**Comment by djimenez** [comment]
the extra changes did bug me a little, I will not complain if you amend them out. 

Thanks.

**Comment by kowalczykp** [comment]
adjusted :)

**Pull request merged**
